import './index.less';
import '../../static-date-picker/style'
import '../../static-date-range-picker/style'
import '../../static-past-time-picker/style'
import '../../button/style';
import '../../input/style';
import '../../list/style';
import '../../popover/style';
import '../../switchGroup/style';