declare module 'rc-notification';
declare module 'rc-upload';
declare module 'rc-util/lib/guid';
declare module '*.png';
declare module '*.svg';
declare module 'rc-calendar';
declare module 'rc-calendar/lib/Picker';
declare module 'rc-calendar/lib/locale/zh_CN';
declare module 'rc-calendar/lib/RangeCalendar';
