name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hey, thank you for opening your first Issue ! 🙂'
          pr-message: 'Hey, thank you for opening your Pull Request !'
